from Widgets.MainForm import Ui_MainWindow as MainFormWidget
from Widgets.DefaultTableViewWidget import Ui_Form as DefaultTableViewWidget
from Widgets.DefaultTreeViewWidget import Ui_Form as DefaultTreeViewWidget
from Widgets.InstrumentAllocationWidget import Ui_Form as InstrumentAllocationWidget
from Widgets.FinancialInstrumentWidget import Ui_Form as FinancialInstrumentWidget